name: Create Pull Request
on: workflow_dispatch
jobs:
  createPullRequest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
